baseURL = 'https://example.org/'
languageCode = 'fr-CA'
title = 'KTFPKNET'
#en-US#My New Hugo Site
[menus]
  [[menus.main]]
    title = "Accueil"
    name = 'Accueil'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    title = "Pages"
    name = 'Pages'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    title = "Catégories"
    name = 'Catégories'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
